packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
  workerd: true

minimumReleaseAgeExclude:
  - "@aws-sdk/client-kms@3.1109.0"
  - "@aws-sdk/client-s3@3.1109.0"
  - "@aws-sdk/lib-storage@3.1109.0"
  - fastify@5.12.0
  - "@cloudflare/vitest-pool-workers@0.21.3"
  - "@cloudflare/workers-types@5.20260814.1"
  - miniflare@5.20260811.1-alpha
  - wrangler@4.123.0

onlyBuiltDependencies:
  - esbuild
overrides:
  undici: 7.29.0
strictDepBuilds: true
