import { RouteBindingSnapshotV1Schema, RouteBindingV1Schema } from "./binding.schema.js";
import {
  CapabilityEvidenceV1Schema,
  ConformanceEvidenceV1Schema,
  ProviderCapabilityDescriptorV1Schema,
  RouteRequirementsV1Schema,
} from "./capability.schema.js";
import {
  BoundedStringMapSchema,
  DomainALabelSchema,
  NormalizedEvidenceSchema,
  Rfc3339TimestampSchema,
  SafeDetailsSchema,
  Sha256Schema,
} from "./common.schema.js";
import { DsnNotifySchema, SmtpEnvelopeV1Schema, SmtpRecipientV1Schema } from "./envelope.schema.js";
import {
  AuditIdSchema,
  AttemptIdSchema,
  BindingIdSchema,
  BlobIdSchema,
  DeliveryIdSchema,
  FeedbackEventIdSchema,
  IdempotencyKeySchema,
  IntentIdSchema,
  ProviderIdSchema,
  ProviderInstanceIdSchema,
  RawAccessGrantIdSchema,
  ReceiptIdSchema,
  TenantIdSchema,
} from "./identifiers.schema.js";
import { DeliveryCertaintySchema, MailEdgeProblemV1Schema } from "./problem.schema.js";
import { RawMessageRefV1Schema } from "./raw.schema.js";
import {
  AuditEventV1Schema,
  ApplicationDeliveryV1Schema,
  ApplicationFeedbackV1Schema,
  IdempotencyRecordV1Schema,
  OutboundAttemptV1Schema,
  OutboundIntentV1Schema,
  OutboundSubmissionV1Schema,
  ProviderAcceptanceV1Schema,
  ProviderFeedbackV1Schema,
  ProviderRecipientOutcomeV1Schema,
  RawAccessGrantV1Schema,
  RecipientDeliveryProjectionV1Schema,
  VerifiedInboundReceiptV1Schema,
  WorkflowWakeupV1Schema,
} from "./workflow.schema.js";

/** Deterministically ordered registry of every public runtime schema. @public */
export const contractSchemas = Object.freeze(
  [
    AuditEventV1Schema,
    AuditIdSchema,
    ApplicationDeliveryV1Schema,
    ApplicationFeedbackV1Schema,
    AttemptIdSchema,
    BindingIdSchema,
    BlobIdSchema,
    BoundedStringMapSchema,
    CapabilityEvidenceV1Schema,
    ConformanceEvidenceV1Schema,
    DeliveryCertaintySchema,
    DeliveryIdSchema,
    DomainALabelSchema,
    DsnNotifySchema,
    FeedbackEventIdSchema,
    IdempotencyKeySchema,
    IdempotencyRecordV1Schema,
    IntentIdSchema,
    MailEdgeProblemV1Schema,
    NormalizedEvidenceSchema,
    OutboundAttemptV1Schema,
    OutboundIntentV1Schema,
    OutboundSubmissionV1Schema,
    ProviderAcceptanceV1Schema,
    ProviderCapabilityDescriptorV1Schema,
    ProviderFeedbackV1Schema,
    ProviderIdSchema,
    ProviderInstanceIdSchema,
    ProviderRecipientOutcomeV1Schema,
    RawAccessGrantIdSchema,
    RawAccessGrantV1Schema,
    RawMessageRefV1Schema,
    ReceiptIdSchema,
    RecipientDeliveryProjectionV1Schema,
    Rfc3339TimestampSchema,
    RouteBindingSnapshotV1Schema,
    RouteBindingV1Schema,
    RouteRequirementsV1Schema,
    SafeDetailsSchema,
    Sha256Schema,
    SmtpEnvelopeV1Schema,
    SmtpRecipientV1Schema,
    TenantIdSchema,
    VerifiedInboundReceiptV1Schema,
    WorkflowWakeupV1Schema,
  ].toSorted((left, right) => String(left.$id).localeCompare(String(right.$id))),
);
